### ISSUE TITLE
MMF and asymmetry parameter

### ISSUE THREAD

**Issue by joolof** [cdominik/optool#2]
Hi Carsten,

First of all, thanks a lot for providing such an excellent tool. Very easy to use and fast!

I was playing around with the MMF option, and I was wondering if there was a way to avoid Delta phi being larger than 1 at short wavelengths. I would like to compute the beta value for the radiation pressure and need the asymmetry parameter which apparently cannot be trusted in some cases. Decreasing the size of a_0 seems to help but I would need to have very small a_0 (e.g., 0.01 microns). It is the first time I'm trying MMF so I may be missing something, but is there another parameter I could change to avoid this issue?

The other comment, or rather small request; would it be possible to have a keyword for a "silent/verbose" mode, where only warnings and errors are printed?

Cheers,
Johan

**Comment by cdominik** [comment]
Hi Johan,

I will get back to you about MMF.  Just a quick answer about the output.  There is an undocumented option "-q", can you try and check if that reduces the output in a sufficient way?  If not, what else is in your way?

Carsten

**Comment by joolof** [comment]
Hi Carsten,
Thanks for the quick answer, the "-q" is exactly what I was looking for.
Johan

**Comment by cdominik** [comment]
Hi Joolof,

some more answers, I am relaying this from Ryo Tazaki:

The phase shift parameter (Delta phi) is defined by Eq. (9) in Tazaki &
Tanaka (2018), and this equation shows that Delta phi is inversely
proportional to the wavelength. Therefore, a larger Delta phi value at
shorter wavelengths is inevitable. In other words, multiple scattering
within an aggregate is essential at shorter wavelengths.

However, there are still some tricks to relax this issue by reducing
monomer radius (as you did), aggregate radius, or the refractive index.
Also, if you consider a fractal dimension larger than 2, reducing the
fractal dimension would also result in reducing Delta phi. When a fractal
dimension is smaller than 2, it has basically nothing to do with the Delta
phi value.


Kind regards

Carsten Dominik

**Comment by joolof** [comment]
Thanks for the clarification Carsten and thanks again for a very useful tool.
Cheers,
Johan
