### ISSUE TITLE
Error: Unexpected end of file in ‘optool_refind.f90’

### ISSUE THREAD

**Issue by Adbhavna1369** [cdominik/optool#3]
Hi Dominick,

This is an attempt to add other datasets with the refractive indices of ferro-magnesium oxides.
The code crashes at make multi = true. I am uploading the files where it has ingested some changes but has not completely added the datasets as compared to the other molecules already in the system.
I have received the following errors:

1. Error: Unexpected character in variable list at (1)
2. Error: Expecting END PROGRAM statement at (1)

 Any advice? 

![image](https://github.com/cdominik/optool/assets/73185067/9e59f820-96c4-49c5-8d4d-57cf97fe7b9d)
![image](https://github.com/cdominik/optool/assets/73185067/de1daaf4-058b-4e9f-ae4c-45af70560705)
![image](https://github.com/cdominik/optool/assets/73185067/e10c463a-7a77-498c-a131-7628dd6021a8)

Please redirect your reply to adbhavna1369@gmail.com for further clarification.

**Comment by cdominik** [comment]
Hi,

can you please send me the files you are trying to add, and your modified
version of the help text file?

Thx.

Carsten

**Comment by Adbhavna1369** [comment]
I found a few mistakes and changes on my end. 
1) No "." should be used when naming the external files when ingesting them in Optool.
2) Carsten mentioned, "You need to clean up first by running
     **make clean**
and then compile again
    **make multi=true**
Basically, whenever you are changing the compilation features by changing the arguments to the "make" call, you should first run "make clean" to make sure all files compile in the same environment." As the program was not installing in the same environment.
3) Use **./optool** to start the program if it does not respond to **optool**.
4) In case if the files do not copy in the **/bin** folder, go to the directory where the repository is cloned(in my case, it was a folder named **optool** itself, manually copy the files into the bin folder, 
**cd optool 
sudo cp optool2tex optool-complete /usr/bin**. I found this better than changing the Makefile.


Thankyou @cdominik :)
